services:
  mlflow_example:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ml_service:local
    container_name: ml_service_local
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8890:8890"
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      DEFAULT_RUN_ID: ${DEFAULT_RUN_ID}
      EVIDENTLY_URL: http://158.160.2.37:8000/
      EVIDENTLY_PROJECT_ID: 019d061f-cc08-7b5e-b932-d792a1f258e2
      DRIFT_BATCH_SIZE: 100
      DRIFT_INTERVAL_SEC: 300
    command: uvicorn main:app --host 0.0.0.0 --port 8890